# Generated by Django 4.1.7 on 2023-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_event_footfall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='footfall',
        ),
    ]
