# Generated by Django 4.1.7 on 2023-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_remove_event_date_remove_event_footfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='footfall',
            field=models.IntegerField(default=0),
        ),
    ]
