# Generated by Django 4.1.7 on 2023-03-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_event_date_event_footfall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
