# Generated by Django 4.1.7 on 2023-03-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
